modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/dragon-forge/SolarFluxReborn/issues"
license = "All rights reserved"

[[mods]]
modId = "solarflux"
version = "${file.jarVersion}"
displayName = "Solar Flux Reborn"
updateJSONURL = "https://h.zeith.org/api/fmluc/246974"
displayURL = "https://h.zeith.org/api/fmlhp/246974"
# logoFile="assets/solarflux/textures/logo.png"
credits = "Nauktis for original Solar Flux for 1.7"
authors = "Zeitheron"

description = '''
Solar Flux Reborn is aimed at implementing easy-to-use solar panels and providing modpack devs the ability to create their own panels with ease!
'''

[[dependencies.solarflux]]
modId = "forge"
mandatory = true
versionRange = "[44.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.solarflux]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"

[[dependencies.solarflux]]
modId = "hammerlib"
mandatory = true
versionRange = "[19.5.56,)"
ordering = "NONE"
side = "BOTH"
